version: '3.5'

services:

    postgres:
        container_name: icea-gestao-postgres
        image: postgres:12.5
        environment:
            - POSTGRES_USER=admicea
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=postgres
        volumes:
            - "./database:/var/lib/postgresql/data"
        ports:
            - 5432:5432
        networks:
            - postgresnetwork
        

    api:
        container_name: icea-gestao-backend
        depends_on: [postgres]
        build:
            context: https://raw.githubusercontent.com/rodrigoengelberg/icea-gestao-backend/main/Dockerfile
        working_dir: /api
        environment:
            - DATABASE_URL=postgres://admicea:1234@localhost:5432/postgres
            - DB_SERVER=postgres
            - DB_PORT=5432
            - DB_NAME=postgres
            - DB_USER=admicea
            - DB_PASSWORD=1234
            - FRONT_SERVER=http://localhost:8801
            - SSL_REJECT=false
        ports:
            - 8800:3333
        networks:
            - postgresnetwork

    front:
        container_name: icea-gestao-front
        build:
            context: https://raw.githubusercontent.com/rodrigoengelberg/icea-gestao-frontend/main/Dockerfile
            args:
                react_app_front_name: ICEA Gestão
                react_app_api_url: http://localhost:8800/api
        working_dir: /front
        ports:
            - 8801:3005
        networks:
            - postgresnetwork

    pgadmin:
        container_name: icea-gestao-pgadmin
        image: dpage/pgadmin4
        ports:
            - 8802:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@icea-gestao.com.br
            - PGADMIN_DEFAULT_PASSWORD=postgres
        networks:
            - postgresnetwork

networks:
    postgresnetwork:
        driver: bridge
